# Generated by Django 4.2.20 on 2025-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Tizimga kirish uchun foydalaniladigan login (Talaba ID raqami)', max_length=150, unique=True, verbose_name='Foydalanuvchi nomi (login)')),
                ('student_id_number', models.CharField(blank=True, help_text='API dan olingan talabaning ID raqami', max_length=50, null=True, unique=True, verbose_name='Talaba ID raqami (API)')),
                ('api_user_hash', models.CharField(blank=True, help_text='API dagi foydalanuvchi uchun unikal SHA256 hash', max_length=255, null=True, unique=True, verbose_name='API foydalanuvchi hash')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiyasi')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi')),
                ('full_name_api', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq F.I.Sh. (API)")),
                ('short_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qisqa F.I.Sh. (API)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Talabning surati (URL)')),
                ('birth_date_timestamp', models.BigIntegerField(blank=True, null=True, verbose_name="Tug'ilgan sana (timestamp)")),
                ('passport_pin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasport PIN')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasport raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon raqami')),
                ('gender_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Jinsi kodi')),
                ('gender_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jinsi')),
                ('university_name_api', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universitet nomi (API)')),
                ('specialty_id_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mutaxassislik ID (API)')),
                ('specialty_code_api', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mutaxassislik kodi (API)')),
                ('specialty_name_api', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassislik nomi (API)')),
                ('student_status_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talaba status kodi')),
                ('student_status_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Talaba statusi')),
                ('education_form_code', models.CharField(blank=True, max_length=10, null=True, verbose_name="Ta'lim shakli kodi")),
                ('education_form_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim shakli")),
                ('education_type_code', models.CharField(blank=True, max_length=10, null=True, verbose_name="Ta'lim turi kodi")),
                ('education_type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ta'lim turi")),
                ('payment_form_code', models.CharField(blank=True, max_length=10, null=True, verbose_name="To'lov shakli kodi")),
                ('payment_form_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="To'lov shakli")),
                ('group_id_api', models.IntegerField(blank=True, null=True, verbose_name='Guruh ID (API)')),
                ('group_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh nomi (API)')),
                ('group_education_lang_code', models.CharField(blank=True, max_length=10, null=True, verbose_name="Guruh ta'lim tili kodi")),
                ('group_education_lang_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Guruh ta'lim tili")),
                ('faculty_id_api', models.IntegerField(blank=True, null=True, verbose_name='Fakultet ID (API)')),
                ('faculty_name_api', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakultet nomi (API)')),
                ('faculty_code_api', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fakultet kodi (API)')),
                ('education_lang_code', models.CharField(blank=True, max_length=10, null=True, verbose_name="Ta'lim tili kodi")),
                ('education_lang_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ta'lim tili")),
                ('level_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kurs kodi')),
                ('level_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kurs nomi')),
                ('semester_id_api', models.IntegerField(blank=True, null=True, verbose_name='Semestr ID (API)')),
                ('semester_code_api', models.CharField(blank=True, max_length=10, null=True, verbose_name='Semestr kodi (API)')),
                ('semester_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Semestr nomi (API)')),
                ('semester_is_current', models.BooleanField(blank=True, null=True, verbose_name='Joriy semestr')),
                ('semester_education_year_code', models.CharField(blank=True, max_length=20, null=True, verbose_name="Semestr o'quv yili kodi")),
                ('semester_education_year_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Semestr o'quv yili nomi")),
                ('semester_education_year_is_current', models.BooleanField(blank=True, null=True, verbose_name="Joriy o'quv yili (semestr)")),
                ('avg_gpa', models.CharField(blank=True, max_length=10, null=True, verbose_name="O'rtacha ball (GPA)")),
                ('password_is_valid_api', models.BooleanField(blank=True, null=True, verbose_name="Parol to'g'riligi (API)")),
                ('address_api', models.TextField(blank=True, null=True, verbose_name='Manzil (API)')),
                ('country_code_api', models.CharField(blank=True, max_length=10, null=True, verbose_name='Davlat kodi (API)')),
                ('country_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Davlat nomi (API)')),
                ('province_code_api', models.CharField(blank=True, max_length=20, null=True, verbose_name='Viloyat kodi (API)')),
                ('province_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat nomi (API)')),
                ('district_code_api', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tuman kodi (API)')),
                ('district_name_api', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman nomi (API)')),
                ('social_category_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ijtimoiy toifa kodi')),
                ('social_category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ijtimoiy toifa nomi')),
                ('accommodation_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Turar joy kodi')),
                ('accommodation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Turar joy nomi')),
                ('validate_url_api', models.URLField(blank=True, max_length=500, null=True, verbose_name='Validatsiya havolasi (API)')),
                ('last_login_api', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish (API)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Talaba (API)',
                'verbose_name_plural': 'Talabalar (API)',
                'ordering': ['-updated_at', 'last_name', 'first_name'],
            },
        ),
    ]
