# Generated by Django 4.2.20 on 2025-06-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
