# Generated by Django 4.2.20 on 2025-06-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test sarlavhasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, help_text='Testni ishlash uchun ajratilgan umumiy vaqt. 0 - cheklanmagan.', verbose_name='Vaqt chegarasi (daqiqa)')),
                ('pass_percentage', models.PositiveSmallIntegerField(default=55, help_text="Testdan o'tish uchun to'plash kerak bo'lgan minimal foiz.", verbose_name="O'tish bali (foizda)")),
                ('is_active', models.BooleanField(default=False, help_text="Talabalar uchun ko'rinadigan qilib belgilash.", verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Yaratuvchi (o'qituvchi/admin)")),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Tugatilgan')], default='in_progress', max_length=20, verbose_name='Holati')),
                ('score', models.FloatField(default=0, verbose_name="To'plangan ball")),
                ('percentage', models.FloatField(default=0, verbose_name='Natija (foizda)')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tganligi")),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqti')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='auth_app.student', verbose_name='Talaba')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='auth_app.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test Urinishi',
                'verbose_name_plural': 'Test Urinishlari',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('single_choice', "Bitta to'g'ri javob"), ('multiple_choice', "Bir nechta to'g'ri javob"), ('open_text', 'Ochiq matnli javob')], default='single_choice', max_length=20, verbose_name='Savol turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Rasm')),
                ('points', models.PositiveSmallIntegerField(default=1, help_text='Ushbu savol uchun beriladigan ball.', verbose_name='Ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auth_app.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'riligi")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_app.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_answer_text', models.TextField(blank=True, null=True, verbose_name='Ochiq javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'riligi")),
                ('points_earned', models.PositiveSmallIntegerField(default=0, verbose_name='Olingan ball')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='auth_app.testattempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.question', verbose_name='Savol')),
                ('selected_answers', models.ManyToManyField(blank=True, to='auth_app.answer', verbose_name='Tanlangan javob(lar)')),
            ],
            options={
                'verbose_name': 'Talaba javobi',
                'verbose_name_plural': 'Talabalar javoblari',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
