# Generated by Django 4.2.20 on 2025-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Kurs kodi (API)')),
                ('name', models.CharField(max_length=50, verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': "Kurs (ma'lumotnoma)",
                'verbose_name_plural': "Kurslar (ma'lumotnoma)",
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text="Test faqat tanlangan kurs talabalari uchun ochiq bo'ladi.", to='auth_app.level', verbose_name='Ruxsat etilgan kurslar'),
        ),
    ]
