# Generated by Django 4.2.20 on 2025-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_level_test_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='allowed_ips',
            field=models.CharField(blank=True, help_text="Testni faqat shu IP manzillardan topshirish mumkin. IP manzillarni vergul bilan ajrating. Bo'sh qoldirilsa - cheklov yo'q.", max_length=500, verbose_name='Ruxsat etilgan IP manzillar'),
        ),
    ]
