# Generated by Django 4.2.20 on 2025-07-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_test_allowed_ips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='auth_app_te_status_14a976_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='auth_app_te_creator_d37460_idx',
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
    ]
